email:
  smtp_host: smtp.gmail.com
  smtp_port: 465
max_retries: 5
monitors:
- name: Pokemon Center - Elite Trainer Box
  url: https://www.pokemoncenter.com/en-gb/category/elite-trainer-box
  site: pokemoncenter
  interval: 10.0
- name: Pokemon Center - Trading Card Game
  url: https://www.pokemoncenter.com/en-gb/category/trading-card-game
  site: pokemoncenter
  keywords:
  - Ascending Heroes
  interval: 10.0
